sudo: required
# super user permissions required to run this build

services:
  - docker 
  # automatically install Docker into our running container

before_install:
  - docker build -t ryangdb/docker-react -f Dockerfile.dev .
  # creates the docker image
  # tag is only going to be used with travis
  # executed before our tests are ran
  # setup required before we deploy our project / run our tests

  script:
    - docker run -e CI=true ryangdb/docker-react npm run test
    # these commands are used to run the test suite
    # if any of these commands return a status code which is not 0
    # then travis is going to assume that something was not successful 
    # travis is also going to assume that the tests exit automatically
    # -- --coverage (can be used to close out of the docker test suite)